{
  "openapi": "3.0.1",
  "paths": {
    "/users": {
      "get": {
        "summary": "Retrieves all users",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "List of all users",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "company_name": {
                        "type": "string"
                      },
                      "address": {
                        "type": "object",
                        "properties": {
                          "street": {
                            "type": "string"
                          },
                          "suite": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "zipcode": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/search": {
      "get": {
        "summary": "Searches for users based on criteria",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Name of the user",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "required": false,
            "description": "Email of the user",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "phone",
            "in": "query",
            "required": false,
            "description": "Phone number of the user",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "zipcode",
            "in": "query",
            "required": false,
            "description": "Zip code of the user address",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "company_name",
            "in": "query",
            "required": false,
            "description": "Company name of the user",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "street",
            "in": "query",
            "required": false,
            "description": "Street of the user address",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Users found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "company_name": {
                        "type": "string"
                      },
                      "address": {
                        "type": "object",
                        "properties": {
                          "street": {
                            "type": "string"
                          },
                          "suite": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "zipcode": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No users found"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    }
  }
}